export const STORAGE_KEYS = Object.freeze({
  PANEL_POSITION: 'CORREIOS_WIZARD::PANEL_POSITION',
  AUTO_CLOSE_PRINT: 'CORREIOS_WIZARD::AUTO_CLOSE_PRINT',
  REMOTE_STATUS_CACHE: 'CORREIOS_WIZARD::REMOTE_STATUS_CACHE'
});
