import { RUNTIME_DEFAULTS } from '../../config/defaults.js';

export const SROWEB_ORIGIN = RUNTIME_DEFAULTS.URLS.SROWEB_ORIGIN;
export const SROINTRANET_ORIGIN = RUNTIME_DEFAULTS.URLS.SROINTRANET_ORIGIN;
export const SROMONITOR_ORIGIN = RUNTIME_DEFAULTS.URLS.SROMONITOR_ORIGIN;

export const FETCH_REQ_EVENT = RUNTIME_DEFAULTS.EVENTS.FETCH_REQ;
export const FETCH_RES_EVENT = RUNTIME_DEFAULTS.EVENTS.FETCH_RES;
export const FETCH_PROXY_ACTION = RUNTIME_DEFAULTS.ACTIONS.FETCH_PROXY;
